### ISSUE TITLE
Setup Dockerfile and Docker-compose.yaml file 

### ISSUE THREAD

**Issue by Aju100** [Aju100/django_todo#10]

**Comment by viagostini** [comment]
Hey, I would like to help you on this one if that's okay :+1:

**Comment by Aju100** [comment]
@viagostini  sure.

**Comment by vinhyenvodoi98** [comment]
i just create pull request check it

**Comment by vinhyenvodoi98** [comment]
@Aju100 not sure but i run `python manage.py runserver 0.0.0.0:8000` 
and open localhost:8000 
![image](https://user-images.githubusercontent.com/33363513/94884610-2491b100-0498-11eb-98a3-d112f820c106.png)
correct me if i wrong

**Comment by Aju100** [comment]
@viagostini  thank you

**Comment by viagostini** [comment]
You should not assign someone to an issue and accept a PR from someone else in the meantime, but oh well
