### ISSUE TITLE
fix: Audit requirements.txt

### ISSUE THREAD

**Issue by Aju100** [Aju100/django_todo#11]
The django_todo project should be migrated from Django 2.x to 3.x

**Comment by saravananselvamohan** [comment]
@Aju100 . Would like to work here and also will you brief the changes need to be done

**Comment by Aju100** [comment]
@saravananselvamohan  before auditing the requirements.txt. You have to migrate django project 2.x version to 3.x version. And you can audit the requirements.txt with the django==3.x and other updated packages.
