### ISSUE TITLE
Remove db.sqlite3

### ISSUE THREAD

**Issue by Aju100** [Aju100/django_todo#5]

**Comment by divya144** [comment]
I would like to work on this issue.

**Comment by raulsoledispa** [comment]
do you can give me more details?

**Comment by Aju100** [comment]
@raulsoledispa  you just have to delete db.sqlite3 and create updated PR

**Comment by andrewmiko** [comment]
@Aju100 I can contribute on this one. BTW, do you plan to add proper gitignore, editorconfig files? Maybe I can work on this too if you wish.

**Comment by raulsoledispa** [comment]
@Aju100 please assign me to complete the task

**Comment by Aju100** [comment]
@raulsoledispa sure.

**Comment by Aju100** [comment]
Hi @andrewmiko  there, u can add proper gitignore and config file.

**Comment by andrewmiko** [comment]
@Aju100 can you please create new issue for project configuration (editorconfig, gitignore, etc). Thanks.

**Comment by Aju100** [comment]
@andrewmiko  sure.
